package rcrsystem.presentation.view;

import Modelo.Usuario;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.Observable;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import rcrsystem.presentation.controller.Ag_Ed_Usuario_Controlador;
import rcrsystem.presentation.model.Usuario_Modelo;

public class VentanaUsuario extends javax.swing.JDialog implements java.util.Observer {

    Ag_Ed_Usuario_Controlador controlador;
    Usuario_Modelo modelo;
    public static Border BORDER_ERROR = BorderFactory.createLineBorder(Color.red);
    public Border BORDER_NOBORDER;

    public VentanaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/rcrsystem/presentation/view/iconos/logoRCR.png")).getImage());
        setLocationRelativeTo(null);
        BORDER_NOBORDER = this.jTextField_nombre.getBorder();
    }

    public Ag_Ed_Usuario_Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Ag_Ed_Usuario_Controlador controlador) {
        this.controlador = controlador;
    }

    public Usuario_Modelo getModelo() {
        return modelo;
    }

    public void setModelo(Usuario_Modelo modelo) {
        this.modelo = modelo;
        modelo.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_telf = new javax.swing.JTextField();
        jRadioButton_admin = new javax.swing.JRadioButton();
        jRadioButton_compras = new javax.swing.JRadioButton();
        jRadioButton_venta = new javax.swing.JRadioButton();
        jPasswordField_normal = new javax.swing.JPasswordField();
        jPasswordField_confirmar = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jButton_accion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Adminstrar Usuario");

        jLabel1.setText("Identificación:");

        jTextField_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_idKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Teléfono:");

        jLabel4.setText("Permisos:");

        jLabel5.setText("Contraseña:");

        jLabel6.setText("Repita la contraseña:");

        jTextField_telf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telfActionPerformed(evt);
            }
        });
        jTextField_telf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_telfKeyTyped(evt);
            }
        });

        buttonGroup1.add(jRadioButton_admin);
        jRadioButton_admin.setSelected(true);
        jRadioButton_admin.setText("Administrador");

        buttonGroup1.add(jRadioButton_compras);
        jRadioButton_compras.setText("Compras");

        buttonGroup1.add(jRadioButton_venta);
        jRadioButton_venta.setText("Ventas");

        jPasswordField_normal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_normalKeyTyped(evt);
            }
        });

        jPasswordField_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_confirmarActionPerformed(evt);
            }
        });
        jPasswordField_confirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_confirmarKeyTyped(evt);
            }
        });

        jButton_accion.setText("Agregar");
        jButton_accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_accionActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_admin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_compras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_venta))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_id, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_telf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField_confirmar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(jPasswordField_normal, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton_accion)
                        .addGap(63, 63, 63)
                        .addComponent(jButton2)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_telf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton_admin)
                    .addComponent(jRadioButton_compras)
                    .addComponent(jRadioButton_venta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField_normal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_accion)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_confirmarActionPerformed

    private void jButton_accionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_accionActionPerformed
        this.jButton_accion.setEnabled(false);
        controlador.agregar();
        this.jButton_accion.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton_accionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jButton2.setEnabled(false);
        this.setVisible(false);
        this.jButton2.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idKeyTyped

    private void jTextField_telfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telfActionPerformed

    private void jTextField_telfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telfKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telfKeyTyped

    private void jPasswordField_normalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_normalKeyTyped
        if (this.jPasswordField_normal.getText().length() == 6) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordField_normalKeyTyped

    private void jPasswordField_confirmarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_confirmarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_confirmarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton_accion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPasswordField jPasswordField_confirmar;
    public javax.swing.JPasswordField jPasswordField_normal;
    public javax.swing.JRadioButton jRadioButton_admin;
    public javax.swing.JRadioButton jRadioButton_compras;
    public javax.swing.JRadioButton jRadioButton_venta;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField jTextField_id;
    public javax.swing.JTextField jTextField_nombre;
    public javax.swing.JTextField jTextField_telf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(java.util.Observable updatedModel, Object parametros) {
        if (parametros != Usuario_Modelo.ae_usuario_actual) {
            return;
        }
        Usuario usuarioCurrent = modelo.obtener_usuario_actual();
        if (usuarioCurrent == null) {
            this.jTextField_id.setText("");
            this.jTextField_nombre.setText("");
            this.jTextField_telf.setText("");
            this.jRadioButton_admin.setSelected(true);
            this.jPasswordField_normal.setText("");
            this.jPasswordField_confirmar.setText("");
        } else {
            this.jTextField_id.setText(usuarioCurrent.getIdentificacion());
            if (modelo.obtener_errores().get("id") != null) {
                this.jTextField_id.setBorder(BORDER_ERROR);
                this.jTextField_id.setToolTipText(modelo.obtener_errores().get("id"));
            } else {
                this.jTextField_id.setBorder(BORDER_NOBORDER);
                this.jTextField_id.setToolTipText(null);
            }
            this.jTextField_nombre.setText(usuarioCurrent.getNombre());
            if (modelo.obtener_errores().get("nombre") != null) {
                this.jTextField_nombre.setBorder(BORDER_ERROR);
                this.jTextField_nombre.setToolTipText(modelo.obtener_errores().get("nombre"));
            } else {
                this.jTextField_nombre.setBorder(BORDER_NOBORDER);
                this.jTextField_nombre.setToolTipText(null);
            }

            this.jPasswordField_normal.setText(usuarioCurrent.getContraseña());
            if (modelo.obtener_errores().get("contraseña") != null && modelo.obtener_errores().get("confirmar") == null) {
                this.jPasswordField_normal.setBorder(BORDER_ERROR);
                this.jPasswordField_normal.setToolTipText(modelo.obtener_errores().get("contraseña"));
            } else {
                this.jPasswordField_normal.setBorder(BORDER_NOBORDER);
                this.jPasswordField_normal.setToolTipText(null);

            }

            if (modelo.obtener_errores().get("contraseña") != null && modelo.obtener_errores().get("confirmar") != null) {
                if (modelo.obtener_errores().get("contraseña") != null && modelo.obtener_errores().get("confirmar") != null) {
                    this.jPasswordField_normal.setBorder(BORDER_ERROR);
                    this.jPasswordField_normal.setToolTipText(modelo.obtener_errores().get("contraseña"));
                    this.jPasswordField_normal.setText(usuarioCurrent.getContraseña());

                    this.jPasswordField_confirmar.setBorder(BORDER_ERROR);
                    this.jPasswordField_confirmar.setToolTipText(modelo.obtener_errores().get("confirmar"));
                } else {
                    //    this.jPasswordField_normal.setText(usuarioCurrent.getContraseña());
                    this.jPasswordField_normal.setBorder(BORDER_NOBORDER);
                    this.jPasswordField_normal.setToolTipText(null);
                    this.jPasswordField_confirmar.setBorder(BORDER_NOBORDER);
                    this.jPasswordField_confirmar.setToolTipText(null);
                }
            } else if (modelo.obtener_errores().get("confirmar") != null && modelo.obtener_errores().get("contraseña") == null) {
                if (modelo.obtener_errores().get("confirmar") != null && modelo.obtener_errores().get("contraseña") == null) {
                    this.jPasswordField_normal.setText(usuarioCurrent.getContraseña());
                    this.jPasswordField_confirmar.setBorder(BORDER_ERROR);
                    this.jPasswordField_confirmar.setToolTipText(modelo.obtener_errores().get("confirmar"));
                } else {
                    this.jPasswordField_confirmar.setBorder(BORDER_NOBORDER);
                    this.jPasswordField_confirmar.setToolTipText(null);
                }
            } else if (modelo.obtener_errores().get("coinciden") != null) {
                this.jPasswordField_confirmar.setBorder(BORDER_ERROR);
                this.jPasswordField_confirmar.setToolTipText(modelo.obtener_errores().get("coinciden"));
            } else {
                this.jPasswordField_confirmar.setBorder(BORDER_NOBORDER);
                this.jPasswordField_confirmar.setToolTipText(null);
            }
            if (modelo.obtener_errores().get("confirmar") == null && modelo.obtener_errores().get("contraseña") == null && modelo.obtener_errores().get("coinciden") == null) {
                jPasswordField_confirmar.setText(usuarioCurrent.getContraseña());
            }
            if (usuarioCurrent.getPuesto() == 1) {
                this.jRadioButton_admin.setSelected(true);
            } else if (usuarioCurrent.getPuesto() == 2) {
                this.jRadioButton_compras.setSelected(true);
            } else if (usuarioCurrent.getPuesto() == 3) {
                this.jRadioButton_venta.setSelected(true);
            } else if (usuarioCurrent.getPuesto() == 0) {
                this.jRadioButton_admin.setSelected(true);
            }
            if (usuarioCurrent.getNumtelefono() == 0) {
                this.jTextField_telf.setText("");
            } else {
                this.jTextField_telf.setText(String.valueOf(usuarioCurrent.getNumtelefono()));
            }

            if (modelo.obtener_errores().get("telefono") != null) {
                this.jTextField_telf.setBorder(BORDER_ERROR);
                this.jTextField_telf.setToolTipText(modelo.obtener_errores().get("telefono"));
            } else {
                this.jTextField_telf.setBorder(BORDER_NOBORDER);
                this.jTextField_telf.setToolTipText(null);
            }
        }
        /*12344
       if(usuarioCurrent.getIdentificacion().equals("")){
        this.jTextField_id.setText("");
       }
       
       if(usuarioCurrent.getNombre().equals("")){
         this.jTextField_nombre.setText("");
       }
       if(usuarioCurrent.getNumtelefono()==0){
         this.jTextField_telf.setText("");
       }
       if(usuarioCurrent.getPuesto()==0){
       this.jRadioButton_admin.setSelected(true);
       }
       if(usuarioCurrent.getContraseña().equals("")){
        this.jPasswordField_normal.setText("");
        this.jPasswordField_confirmar.setText("");
       }*/
        this.validate();
        if (modelo.obtener_mensaje() != null) {
            if (!modelo.obtener_mensaje().equals("")) {
                JOptionPane.showMessageDialog(this, modelo.obtener_mensaje(), "", JOptionPane.INFORMATION_MESSAGE);
                modelo.colocar_mensaje("");
            }
        }
    }
}
