package rcrsystem.presentation.view;

import Modelo.ListaEmpaque;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import rcrsystem.presentation.controller.Ventas_Controlador;
import rcrsystem.presentation.model.Ventas_Modelo;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import rcrsystem.presentation.controller.Facturar_Controlador;
import rcrsystem.presentation.controller.Progreso_Menu_Prin_Controlador;
import rcrsystem.presentation.controller.Progreso_Venta_Controlador;
import rcrsystem.presentation.controller.Usuario_Controlador;

public class VentanaVenta extends javax.swing.JFrame implements java.util.Observer {

    Ventas_Controlador controlador;
    Ventas_Modelo modelo;
    public static Border BORDER_ERROR = BorderFactory.createLineBorder(Color.red);
    public Border BORDER_NOBORDER;
    VentanaCarga ventana;

    public VentanaVenta() {
        initComponents();
        this.setResizable(false);
        ventana = new VentanaCarga();
        BORDER_NOBORDER = this.año_jTextField.getBorder();
        this.maritimo_jRadioButton.setSelected(true);
        setIconImage(new ImageIcon(getClass().getResource("/rcrsystem/presentation/view/iconos/logoRCR.png")).getImage());
        setLocationRelativeTo(null);

    }

    public Ventas_Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Ventas_Controlador controlador) {
        this.controlador = controlador;
    }

    public Ventas_Modelo getModelo() {
        return modelo;
    }

    public void setModelo(Ventas_Modelo modelo) {
        this.modelo = modelo;
        modelo.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cliente_jComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        destino_jTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        javax.swing.JLabel fecha2 = new javax.swing.JLabel();
        fecha_jLabel = new javax.swing.JLabel();
        numVent_jLabel = new javax.swing.JLabel();
        venta_jLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        terrestre_jRadioButton = new javax.swing.JRadioButton();
        maritimo_jRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        idtrans_jTextField = new javax.swing.JTextField();
        letrero_jLabel = new javax.swing.JLabel();
        nombretrans_jLabel = new javax.swing.JLabel();
        idtrans_jLabel = new javax.swing.JLabel();
        nombreTrans_jTextField = new javax.swing.JTextField();
        nacTrans_jLabel = new javax.swing.JLabel();
        nacionTrans_jTextField = new javax.swing.JTextField();
        fechanac_jLabel = new javax.swing.JLabel();
        dia_jComboBox = new javax.swing.JComboBox<>();
        mes_jComboBox = new javax.swing.JComboBox<>();
        año_jLabel = new javax.swing.JLabel();
        año_jTextField = new javax.swing.JTextField();
        transportista_jPanel = new javax.swing.JPanel();
        chasis_jLabel = new javax.swing.JLabel();
        chasis_jTextField = new javax.swing.JTextField();
        furgon_jLabel = new javax.swing.JLabel();
        furgon_jTextField = new javax.swing.JTextField();
        placa_jLabel = new javax.swing.JLabel();
        placa_jTextField = new javax.swing.JTextField();
        marca_jLabel = new javax.swing.JLabel();
        marca_jTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        numero_jlabel = new javax.swing.JLabel();
        codigo_bultojTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        material_bultojTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipo_boton = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        agregarbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bultos_jTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pesoBruto_jLabel = new javax.swing.JLabel();
        pesoNeto_jTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        eliminar_jButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        confirmar_jButton = new javax.swing.JButton();
        cancelar_jButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btn_cerrar_sesion = new javax.swing.JMenuItem();
        btn_salir = new javax.swing.JMenuItem();
        facturar_jMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        btn_calculadora = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        btn_ayuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ventas");

        jPanel8.setBackground(new java.awt.Color(27, 82, 156));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Cliente:");

        cliente_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cliente_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente_jComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Destino: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cliente_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destino_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cliente_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(destino_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fecha2.setText("Fecha:");

        fecha_jLabel.setText("dd/mm/yyyy");

        numVent_jLabel.setText("Código");

        venta_jLabel.setText("1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numVent_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(venta_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(fecha2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fecha_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fecha2)
                    .addComponent(numVent_jLabel)
                    .addComponent(venta_jLabel))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(terrestre_jRadioButton);
        terrestre_jRadioButton.setText("Terrestre");
        terrestre_jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terrestre_jRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(maritimo_jRadioButton);
        maritimo_jRadioButton.setText("Marítimo");
        maritimo_jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maritimo_jRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de transporte:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(maritimo_jRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(terrestre_jRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maritimo_jRadioButton)
                    .addComponent(terrestre_jRadioButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        idtrans_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idtrans_jTextFieldKeyTyped(evt);
            }
        });

        letrero_jLabel.setText("Conductor:");

        nombretrans_jLabel.setText("Nombre:");

        idtrans_jLabel.setText("Identificación:");

        nombreTrans_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTrans_jTextFieldActionPerformed(evt);
            }
        });
        nombreTrans_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTrans_jTextFieldKeyTyped(evt);
            }
        });

        nacTrans_jLabel.setText("Nacionalidad:");

        nacionTrans_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionTrans_jTextFieldActionPerformed(evt);
            }
        });
        nacionTrans_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nacionTrans_jTextFieldKeyTyped(evt);
            }
        });

        fechanac_jLabel.setText("Fecha de Nacimiento:");

        dia_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dia_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dia_jComboBoxActionPerformed(evt);
            }
        });

        mes_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        mes_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes_jComboBoxActionPerformed(evt);
            }
        });

        año_jLabel.setText("Año:");

        año_jTextField.setMinimumSize(null);
        año_jTextField.setName(""); // NOI18N
        año_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                año_jTextFieldActionPerformed(evt);
            }
        });
        año_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                año_jTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(letrero_jLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombretrans_jLabel)
                            .addComponent(idtrans_jLabel)
                            .addComponent(nacTrans_jLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreTrans_jTextField)
                            .addComponent(idtrans_jTextField)
                            .addComponent(nacionTrans_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fechanac_jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dia_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mes_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(año_jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(año_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(letrero_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTrans_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombretrans_jLabel))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtrans_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtrans_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacionTrans_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacTrans_jLabel))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dia_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(año_jLabel)
                    .addComponent(año_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechanac_jLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        transportista_jPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chasis_jLabel.setText("Chasis:");

        chasis_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chasis_jTextFieldActionPerformed(evt);
            }
        });
        chasis_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chasis_jTextFieldKeyTyped(evt);
            }
        });

        furgon_jLabel.setText("Furgón:");

        furgon_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                furgon_jTextFieldActionPerformed(evt);
            }
        });

        placa_jLabel.setText("Placa:");

        placa_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa_jTextFieldActionPerformed(evt);
            }
        });
        placa_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placa_jTextFieldKeyTyped(evt);
            }
        });

        marca_jLabel.setText("Marca:");

        marca_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marca_jTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Transporte:");

        javax.swing.GroupLayout transportista_jPanelLayout = new javax.swing.GroupLayout(transportista_jPanel);
        transportista_jPanel.setLayout(transportista_jPanelLayout);
        transportista_jPanelLayout.setHorizontalGroup(
            transportista_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transportista_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transportista_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(transportista_jPanelLayout.createSequentialGroup()
                        .addGroup(transportista_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marca_jLabel)
                            .addComponent(placa_jLabel)
                            .addComponent(chasis_jLabel)
                            .addComponent(furgon_jLabel))
                        .addGap(18, 18, 18)
                        .addGroup(transportista_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(placa_jTextField)
                            .addComponent(marca_jTextField)
                            .addComponent(chasis_jTextField)
                            .addComponent(furgon_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transportista_jPanelLayout.setVerticalGroup(
            transportista_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transportista_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transportista_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placa_jTextField)
                    .addComponent(placa_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transportista_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca_jLabel)
                    .addComponent(marca_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transportista_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chasis_jLabel)
                    .addComponent(chasis_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(transportista_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(furgon_jLabel)
                    .addComponent(furgon_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transportista_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(transportista_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(27, 82, 156));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setPreferredSize(new java.awt.Dimension(354, 569));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setText("Código de bulto:");

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Bulto:");

        numero_jlabel.setText("1");

        codigo_bultojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_bultojTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Material:");

        material_bultojTextField.setEnabled(false);

        jLabel5.setText("Tipo:");

        tipo_boton.setEnabled(false);
        tipo_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_botonActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        agregarbtn.setText("Agregar");
        agregarbtn.setEnabled(false);
        agregarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(agregarbtn)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(agregarbtn)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numero_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigo_bultojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipo_boton)
                                    .addComponent(material_bultojTextField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(39, 39, 39)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(numero_jlabel))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(codigo_bultojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(material_bultojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tipo_boton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bultos_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bultos_jTable);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Peso Bruto:");

        jLabel11.setText("Peso Neto:");

        pesoBruto_jLabel.setText("0.0");

        pesoNeto_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoNeto_jTextFieldActionPerformed(evt);
            }
        });
        pesoNeto_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesoNeto_jTextFieldKeyTyped(evt);
            }
        });

        jLabel13.setText("KG");

        jLabel14.setText("KG");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(pesoBruto_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(pesoNeto_jTextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pesoBruto_jLabel)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pesoNeto_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        eliminar_jButton.setBackground(new java.awt.Color(255, 0, 0));
        eliminar_jButton.setText("Eliminar");
        eliminar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(eliminar_jButton))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(eliminar_jButton)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jPanel10.setBackground(new java.awt.Color(27, 82, 156));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        confirmar_jButton.setText("Confirmar");
        confirmar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_jButtonActionPerformed(evt);
            }
        });

        cancelar_jButton.setText("Cancelar");
        cancelar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_jButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(confirmar_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(cancelar_jButton)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmar_jButton)
                    .addComponent(cancelar_jButton)
                    .addComponent(jButton2))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rcrsystem/presentation/view/iconos/folder.png"))); // NOI18N
        jMenu1.setText("Archivo");

        btn_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rcrsystem/presentation/view/iconos/disconnect.png"))); // NOI18N
        btn_cerrar_sesion.setText("Cerrar Sesión");
        btn_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesionActionPerformed(evt);
            }
        });
        jMenu1.add(btn_cerrar_sesion);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rcrsystem/presentation/view/iconos/door_out.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jMenu1.add(btn_salir);

        jMenuBar1.add(jMenu1);

        facturar_jMenu.setText("Facturar");
        facturar_jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturar_jMenuActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Facturar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        facturar_jMenu.add(jMenuItem1);

        jMenuBar1.add(facturar_jMenu);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rcrsystem/presentation/view/iconos/cog.png"))); // NOI18N
        jMenu6.setText("Herramientas");

        btn_calculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rcrsystem/presentation/view/iconos/calculator.png"))); // NOI18N
        btn_calculadora.setText("Calculadora");
        btn_calculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculadoraActionPerformed(evt);
            }
        });
        jMenu6.add(btn_calculadora);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rcrsystem/presentation/view/iconos/help.png"))); // NOI18N
        jMenu7.setText("Ayuda");

        btn_ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rcrsystem/presentation/view/iconos/comment.png"))); // NOI18N
        btn_ayuda.setText("Acerca de");
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });
        jMenu7.add(btn_ayuda);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marca_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marca_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marca_jTextFieldActionPerformed

    private void chasis_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chasis_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chasis_jTextFieldActionPerformed

    private void nacionTrans_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionTrans_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionTrans_jTextFieldActionPerformed

    private void maritimo_jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maritimo_jRadioButtonActionPerformed
        this.jPanel2.setVisible(false);
        this.transportista_jPanel.setVisible(true);
        this.pack();
    }//GEN-LAST:event_maritimo_jRadioButtonActionPerformed

    private void terrestre_jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terrestre_jRadioButtonActionPerformed

        this.jPanel2.setVisible(true);
        this.transportista_jPanel.setVisible(true);
        this.pack();
    }//GEN-LAST:event_terrestre_jRadioButtonActionPerformed

    private void dia_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dia_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dia_jComboBoxActionPerformed

    private void mes_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mes_jComboBoxActionPerformed

    private void cancelar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_jButtonActionPerformed
        Object[] opciones = {"Si", "No"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "¿Desea cancelar el ingreso de la lista de empaque?", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            controlador.eliminar_errores();
            controlador.limpiar_bulto();
            controlador.limpiar_datos();

        }
    }//GEN-LAST:event_cancelar_jButtonActionPerformed

    private void eliminar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_jButtonActionPerformed
        int row = this.bultos_jTable.getSelectedRow();
        this.eliminar_jButton.setEnabled(true);
        controlador.borrar_bulto(row);         // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_jButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jButton1.setEnabled(false);

        Progreso_Venta_Controlador p = new Progreso_Venta_Controlador(ventana, this);
        p.colocar_tipo(1);
        p.execute();

//         controlador.cargar_bulto(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void furgon_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_furgon_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_furgon_jTextFieldActionPerformed

    private void pesoNeto_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoNeto_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoNeto_jTextFieldActionPerformed

    private void confirmar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_jButtonActionPerformed
        /*ventana= new VentanaCarga();
        Progreso_Venta_Controlador p = new Progreso_Venta_Controlador(ventana, this);
        //this.setVisible(false);
        p.colocar_tipo(3);
        p.execute();     */        // TODO add your handling code here:
        pregenerarListaEmpaque();
    }//GEN-LAST:event_confirmar_jButtonActionPerformed

    private void placa_jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placa_jTextFieldKeyTyped

    }//GEN-LAST:event_placa_jTextFieldKeyTyped

    private void chasis_jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chasis_jTextFieldKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_chasis_jTextFieldKeyTyped

    private void idtrans_jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtrans_jTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_idtrans_jTextFieldKeyTyped

    private void pesoNeto_jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesoNeto_jTextFieldKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pesoNeto_jTextFieldKeyTyped

    private void año_jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_año_jTextFieldKeyTyped
        if (this.año_jTextField.getText().length() != 4) {
            if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
                Toolkit.getDefaultToolkit().beep();
                evt.consume();
            }
        } else {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_año_jTextFieldKeyTyped

    private void año_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_año_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_año_jTextFieldActionPerformed

    private void nombreTrans_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTrans_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTrans_jTextFieldActionPerformed

    private void nombreTrans_jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTrans_jTextFieldKeyTyped
        if (Character.isDigit(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTrans_jTextFieldKeyTyped

    private void nacionTrans_jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nacionTrans_jTextFieldKeyTyped
        if (Character.isDigit(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_nacionTrans_jTextFieldKeyTyped

    private void codigo_bultojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_bultojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_bultojTextFieldActionPerformed

    private void tipo_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_botonActionPerformed

    private void agregarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarbtnActionPerformed
        controlador.agregar_bulto();
    }//GEN-LAST:event_agregarbtnActionPerformed

    private void placa_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placa_jTextFieldActionPerformed

    private void btn_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesionActionPerformed
        this.setVisible(false);
        rcrsystem.Aplicacion.ae_usuario = new Usuario();
        rcrsystem.Aplicacion.ae_vista_principal = new VentanaInicio();
        rcrsystem.Aplicacion.ae_vista_principal.setController(new Usuario_Controlador());
        rcrsystem.Aplicacion.ae_vista_principal.setVisible(true);
    }//GEN-LAST:event_btn_cerrar_sesionActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_calculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculadoraActionPerformed
        Process runtimeProcess;
        try {
            System.out.println(System.getProperty("os.name"));
            String comandoCalculadora = System.getProperty("os.name").startsWith("Windows") ? "calc" : "gcalctool";
            runtimeProcess = Runtime.getRuntime().exec(comandoCalculadora);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_calculadoraActionPerformed

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        JOptionPane.showMessageDialog(this, "Estamos trabajando", "error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (rcrsystem.Aplicacion.ae_modelo_factura.getListas().isEmpty()) {
            this.setVisible(false);
            Progreso_Menu_Prin_Controlador v = new Progreso_Menu_Prin_Controlador(ventana);
            v.execute();
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "¡Aún hay listas de empaque por facturar!", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void facturar_jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturar_jMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facturar_jMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        VentanaFacturacion aplicacion = new VentanaFacturacion(this);

        rcrsystem.presentation.model.Facturar_Modelo modelo = new rcrsystem.presentation.model.Facturar_Modelo();

        VentanaFacturacion vista = new VentanaFacturacion(this);
        Facturar_Controlador controlador = new Facturar_Controlador(vista, modelo);
        this.setVisible(false);
        vista.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cliente_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente_jComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVenta().setVisible(true);
            }
        });
    }

    public void cargarBulto(VentanaCarga carga) {
        controlador.cargar_bulto(carga);
    }

    public void agregarBulto() {
        controlador.agregar_bulto();
    }

    public void pregenerarListaEmpaque() {
        if (controlador.validar_lista_empaque()) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que desea ingresar la lista de empaque?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == JOptionPane.YES_OPTION) {
                ventana = new VentanaCarga();
                Progreso_Venta_Controlador p = new Progreso_Venta_Controlador(ventana, this);
                p.colocar_tipo(3);
                p.execute();
                controlador.procesar_lista_empaque(ventana);
            }
        } else {

            controlador.reportar_errores();
        }
    }

    public void generarListaEmpaque() {
        try {
            controlador.guardar_lista_empaque();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarbtn;
    public javax.swing.JLabel año_jLabel;
    public javax.swing.JTextField año_jTextField;
    private javax.swing.JMenuItem btn_ayuda;
    private javax.swing.JMenuItem btn_calculadora;
    private javax.swing.JMenuItem btn_cerrar_sesion;
    private javax.swing.JMenuItem btn_salir;
    public javax.swing.JTable bultos_jTable;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton cancelar_jButton;
    public javax.swing.JLabel chasis_jLabel;
    public javax.swing.JTextField chasis_jTextField;
    public javax.swing.JComboBox<String> cliente_jComboBox;
    public javax.swing.JTextField codigo_bultojTextField;
    public javax.swing.JButton confirmar_jButton;
    public javax.swing.JTextField destino_jTextField;
    public javax.swing.JComboBox<String> dia_jComboBox;
    public javax.swing.JButton eliminar_jButton;
    private javax.swing.JMenu facturar_jMenu;
    public javax.swing.JLabel fecha_jLabel;
    public javax.swing.JLabel fechanac_jLabel;
    public javax.swing.JLabel furgon_jLabel;
    public javax.swing.JTextField furgon_jTextField;
    public javax.swing.JLabel idtrans_jLabel;
    public javax.swing.JTextField idtrans_jTextField;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel letrero_jLabel;
    public javax.swing.JLabel marca_jLabel;
    public javax.swing.JTextField marca_jTextField;
    public javax.swing.JRadioButton maritimo_jRadioButton;
    public javax.swing.JTextField material_bultojTextField;
    public javax.swing.JComboBox<String> mes_jComboBox;
    public javax.swing.JLabel nacTrans_jLabel;
    public javax.swing.JTextField nacionTrans_jTextField;
    public javax.swing.JTextField nombreTrans_jTextField;
    public javax.swing.JLabel nombretrans_jLabel;
    public javax.swing.JLabel numVent_jLabel;
    public javax.swing.JLabel numero_jlabel;
    public javax.swing.JLabel pesoBruto_jLabel;
    public javax.swing.JTextField pesoNeto_jTextField;
    public javax.swing.JLabel placa_jLabel;
    public javax.swing.JTextField placa_jTextField;
    public javax.swing.JRadioButton terrestre_jRadioButton;
    public javax.swing.JTextField tipo_boton;
    public javax.swing.JPanel transportista_jPanel;
    public javax.swing.JLabel venta_jLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(java.util.Observable updatedModel, Object parametros) {

        if (parametros != modelo.ae_modelo_ventas) {
            return;
        }
        ListaEmpaque current = modelo.obtener_actual();

        this.bultos_jTable.setModel(modelo.obtener_modelo_material());

        if (modelo.obtener_errores().get("destino") != null) {
            this.destino_jTextField.setBorder(this.BORDER_ERROR);
            destino_jTextField.setToolTipText(modelo.obtener_errores().get("destino"));
        } else {
            this.destino_jTextField.setText(current.getDestino());
            destino_jTextField.setBorder(BORDER_NOBORDER);
            destino_jTextField.setToolTipText("");
        }
        if (current.getMedioTransporte() == 1) {
            this.maritimo_jRadioButton.setSelected(true);
        } else {
            this.terrestre_jRadioButton.setSelected(true);
        }

        if (!current.getFecha().equals("")) {
            String dia = current.getFecha().substring(0, 2);
            this.dia_jComboBox.setSelectedItem(dia);
            String mes = current.getFecha().substring(3, 5);
            this.mes_jComboBox.setSelectedItem(controlador.mes_numero(mes));
            String año = current.getFecha().substring(6);
        } else {
            this.dia_jComboBox.setSelectedIndex(0);
            this.mes_jComboBox.setSelectedIndex(0);
            this.año_jTextField.setText("");
        }
        if (modelo.obtener_errores().get("año") != null) {
            this.año_jTextField.setBorder(this.BORDER_ERROR);
            año_jTextField.setToolTipText(modelo.obtener_errores().get("año"));
        } else {
            if (!current.getFecha().equals("")) {
                this.año_jTextField.setText(current.getFecha().substring(6));
            } else {
                this.año_jTextField.setText("");
            }
            año_jTextField.setToolTipText("");
            año_jTextField.setBorder(BORDER_NOBORDER);
        }

        if (modelo.obtener_errores().get("placa") != null) {
            this.placa_jTextField.setBorder(this.BORDER_ERROR);
            placa_jTextField.setToolTipText(modelo.obtener_errores().get("placa"));
        } else {
            this.placa_jTextField.setText(current.getPlaca());
            placa_jTextField.setToolTipText("");
            placa_jTextField.setBorder(BORDER_NOBORDER);
        }
        if (modelo.obtener_errores().get("marca") != null) {
            this.marca_jTextField.setBorder(this.BORDER_ERROR);
            marca_jTextField.setToolTipText(modelo.obtener_errores().get("chasis"));
        } else {
            this.marca_jTextField.setText(current.getMarca());
            marca_jTextField.setBorder(BORDER_NOBORDER);
            marca_jTextField.setToolTipText("");
        }
        if (modelo.obtener_errores().get("chasis") != null) {
            this.chasis_jTextField.setBorder(this.BORDER_ERROR);
            chasis_jTextField.setToolTipText(modelo.obtener_errores().get("chasis"));
        } else {
            this.chasis_jTextField.setText(current.getChasis());
            chasis_jTextField.setBorder(BORDER_NOBORDER);
            chasis_jTextField.setToolTipText("");
        }
        if (modelo.obtener_errores().get("furgon") != null) {
            this.furgon_jTextField.setBorder(this.BORDER_ERROR);
            furgon_jTextField.setToolTipText(modelo.obtener_errores().get("furgon"));
        } else {
            this.furgon_jTextField.setText(current.getFurgon());
            furgon_jTextField.setBorder(BORDER_NOBORDER);
            furgon_jTextField.setToolTipText("");
        }

        if (modelo.obtener_errores().get("nombreT") != null) {
            this.nombreTrans_jTextField.setBorder(this.BORDER_ERROR);
            nombreTrans_jTextField.setToolTipText(modelo.obtener_errores().get("nombreT"));
        } else {

            nombreTrans_jTextField.setBorder(BORDER_NOBORDER);
            this.nombreTrans_jTextField.setText(current.getConductor().getNombre());
            nombreTrans_jTextField.setToolTipText("");
        }
        if (modelo.obtener_errores().get("nacionalidadT") != null) {
            this.nacionTrans_jTextField.setBorder(this.BORDER_ERROR);
            nacionTrans_jTextField.setToolTipText(modelo.obtener_errores().get("nacionalidadT"));
        } else {
            this.nacionTrans_jTextField.setText(current.getConductor().getNacionalidad());
            nacionTrans_jTextField.setBorder(this.BORDER_NOBORDER);
            nacionTrans_jTextField.setToolTipText("");
        }

        this.pesoBruto_jLabel.setText(String.valueOf(current.getPesoBruto()));
        if (modelo.obtener_errores().get("idT") != null) {
            this.idtrans_jTextField.setBorder(this.BORDER_ERROR);
            idtrans_jTextField.setToolTipText(modelo.obtener_errores().get("idT"));
        } else {
            this.idtrans_jTextField.setText(String.valueOf(current.getConductor().getId()));
            idtrans_jTextField.setBorder(BORDER_NOBORDER);
            idtrans_jTextField.setToolTipText("");
        }

        if (modelo.obtener_errores().get("peso") != null) {
            this.pesoNeto_jTextField.setBorder(this.BORDER_ERROR);
            pesoNeto_jTextField.setToolTipText(modelo.obtener_errores().get("peso"));
        } else {
            if (current.getPesoNeto() == 0.0) {
                this.pesoNeto_jTextField.setText("");
            } else {
                this.pesoNeto_jTextField.setText(String.valueOf(current.getPesoNeto()));
            }
            pesoNeto_jTextField.setBorder(this.BORDER_NOBORDER);
            pesoNeto_jTextField.setToolTipText("");
        }
        this.pesoBruto_jLabel.setText(String.valueOf(controlador.obtener_peso_bruto()));
        controlador.definir_cliente(current.getCliente());

        if (current.getMedioTransporte() == 1) {
            this.jPanel2.setVisible(false);
            this.transportista_jPanel.setVisible(true);
        } else {
            this.jPanel2.setVisible(true);
            this.transportista_jPanel.setVisible(true);

        }
        this.validate();
        if (!modelo.obtener_mensaje().equals("")) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, modelo.obtener_mensaje(), "", JOptionPane.INFORMATION_MESSAGE);
            modelo.colocar_mensaje("");
        }
    }
}
